services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    env_file: .env.production
    secrets:
      - postgres_password
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: nexusdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_password

  redis:
    image: redis:7
    restart: always

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  pgdata:
